# Generated by Django 5.2.8 on 2025-11-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_anonymouscartitem_id_alter_cartitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Uncategorized', help_text='e.g. Top, Bottom, Dress, Accessories', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(default='General', help_text='e.g. Summer, Fancy, Casual, Formal', max_length=50),
        ),
    ]
